% Check, which trajectories have two data points in the same frame (which
% is an obvious error)
%
% Input:
%   trajs : structure array such as generated by clusters2trajs
%
% Output:
%   dupl : array containing the ids of trajectories with doubled data
%
% (c) Simon Grosse-Holz, 2020

function dupl = duplicate_times(trajs)
    dupl = [];
    for i = 1:length(trajs)
        traj = trajs(i);
        if length(traj.t) ~= length(unique(traj.t))
            dupl = [dupl, traj.id];
        end
    end
end
